[package]
name = "first-person-explorer"
version = "0.1.0"
authors = ["Rick Waterman <rwaterman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
